# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Helper utility to get temporary credentials from AWS SSO."
  homepage "https://google.com"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.0.0/aws-sso-creds-v2.0.0-darwin-arm64.tar.gz"
      sha256 "b70347700ec4db675d61580f816a281a94aff47ca990ec6513cee9b8e808d257"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.0.0/aws-sso-creds-v2.0.0-darwin-amd64.tar.gz"
      sha256 "74163bc3cf229468b4cc8dc933cd4d7e4f83b98ee5a5170e2ed81ebb5995f1a6"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.0.0/aws-sso-creds-v2.0.0-linux-arm64.tar.gz"
      sha256 "a4d0290ff7187e2f57e9b3db9d40805c728d17984aa87acda14b8f7ee7df00db"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.0.0/aws-sso-creds-v2.0.0-linux-amd64.tar.gz"
      sha256 "4e2e23d0fa60d075d67c6d9cf60d075b91ed426ec07e4b1852f9b67ce6195284"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end
end
