# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoCreds < Formula
  desc "Helper utility to get temporary credentials from AWS SSO."
  homepage "https://google.com"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.1.0/aws-sso-creds-v2.1.0-darwin-arm64.tar.gz"
      sha256 "cd676117697ff742994bb1ac5026fa9c69aed1c50fa5c0032a06c48ac0ec6817"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.1.0/aws-sso-creds-v2.1.0-darwin-amd64.tar.gz"
      sha256 "2e204abda8e4cf5238b268d23059a04d913af59c3b132fda4692cef0aa33c1db"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.1.0/aws-sso-creds-v2.1.0-linux-arm64.tar.gz"
      sha256 "ab0f7ae2a871f1a68be03ceaeea2a2bacbae2bf107ada2190009b3ac0fa8fb19"

      def install
        bin.install "aws-sso-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kenXengineering/aws-sso-creds/releases/download/v2.1.0/aws-sso-creds-v2.1.0-linux-amd64.tar.gz"
      sha256 "7621df8135357f0ff284160f54e0e3ce28c2fc4424a9e2df59685861b6a6e64f"

      def install
        bin.install "aws-sso-creds"
      end
    end
  end
end
